"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 22:37:03.887521
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_throttle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_throttle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_throttle_key'), ['key'], unique=True)

    op.create_table('record_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_epoch', sa.Integer(), nullable=True),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('totp_last_step', sa.Integer(), nullable=True),
    sa.Column('totp_recovery', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('consumer_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('record_type_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('number_normalized', sa.String(length=40), nullable=False),
    sa.Column('internal_code', sa.String(length=60), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('due_ack', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_type_id'], ['record_types.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumer_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumer_units_number_normalized'), ['number_normalized'], unique=True)
        batch_op.create_index(batch_op.f('ix_consumer_units_store_id'), ['store_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)

    op.create_table('energy_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('record_type_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.Date(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=True),
    sa.Column('series', sa.String(length=20), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('previous_reading_date', sa.Date(), nullable=True),
    sa.Column('current_reading_date', sa.Date(), nullable=True),
    sa.Column('next_reading_date', sa.Date(), nullable=True),
    sa.Column('consumption_hp', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('consumption_hfp', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('consumption_kwh', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('consumption_hr', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('demand_hp', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('demand_hfp', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('contracted_demand', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('pis_cofins_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('icms_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bill_class', sa.String(length=80), nullable=True),
    sa.Column('subclass', sa.String(length=120), nullable=True),
    sa.Column('tariff_modality', sa.String(length=80), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['record_type_id'], ['record_types.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['consumer_units.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_bills_record_type_id'), ['record_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_bills_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_bills_unit_id'), ['unit_id'], unique=False)

    op.create_table('manual_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('record_type_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['record_type_id'], ['record_types.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['consumer_units.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_records_record_type_id'), ['record_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_records_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_records_store_id'), ['store_id'], unique=False)

    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('store_hint_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('matched_unit_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['energy_bills.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['matched_unit_id'], ['consumer_units.id'], ),
    sa.ForeignKeyConstraint(['store_hint_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imports_status'))

    op.drop_table('imports')
    with op.batch_alter_table('manual_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_records_store_id'))
        batch_op.drop_index(batch_op.f('ix_manual_records_reference'))
        batch_op.drop_index(batch_op.f('ix_manual_records_record_type_id'))

    op.drop_table('manual_records')
    with op.batch_alter_table('energy_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_bills_unit_id'))
        batch_op.drop_index(batch_op.f('ix_energy_bills_reference'))
        batch_op.drop_index(batch_op.f('ix_energy_bills_record_type_id'))

    op.drop_table('energy_bills')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))

    op.drop_table('documents')
    with op.batch_alter_table('consumer_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumer_units_store_id'))
        batch_op.drop_index(batch_op.f('ix_consumer_units_number_normalized'))

    op.drop_table('consumer_units')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('record_types')
    with op.batch_alter_table('login_throttle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_throttle_key'))

    op.drop_table('login_throttle')
    # ### end Alembic commands ###
