"""alert_acks

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-10 00:05:29.156068
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    if "alert_acks" in sa.inspect(op.get_bind()).get_table_names():      # banco já criado com o modelo atual
        return
    op.create_table('alert_acks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('by_user', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['by_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_acks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_acks_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_acks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_acks_key'))

    op.drop_table('alert_acks')
    # ### end Alembic commands ###
