"""manual_accounting_date

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-10 00:22:47.301163
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    if any(c["name"] == "accounting_date" for c in sa.inspect(op.get_bind()).get_columns("manual_records")):
        return                                           # banco já com a coluna (criado com o modelo atual)
    with op.batch_alter_table('manual_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accounting_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_records', schema=None) as batch_op:
        batch_op.drop_column('accounting_date')

    # ### end Alembic commands ###
